# Generated by Django 4.1.2 on 2022-10-20 19:01

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(default='vacancies/logo/default/default.png', upload_to='vacancies/logo/', verbose_name='company logo')),
                ('company_name', models.CharField(max_length=50, verbose_name='company name')),
                ('description', models.TextField(verbose_name='description')),
                ('to_apply', models.URLField(verbose_name='where to apply (URL)')),
                ('company_website', models.URLField(verbose_name='company website URL')),
                ('company_twitter', models.URLField(verbose_name='company twitter URL')),
                ('communication', models.TextField(verbose_name='data for getting in touch with you')),
                ('verified', models.BooleanField(default=False, verbose_name='company is verified? (admin)')),
                ('hot', models.BooleanField(default=False, verbose_name='vacancy is hot? (payment to admins)')),
                ('archived', models.BooleanField(default=False, verbose_name='vacancy is archived? (payment)')),
                ('job_type', models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('up2u', 'UP2U'), ('temporary', 'Temporary')], default='fulltime', max_length=50, verbose_name='job type')),
                ('salary_type', models.CharField(choices=[('cash', 'Cash'), ('stablecoins', 'Stablecoins'), ('crypto', 'Crypto'), ('your_tokens', 'Your Tokens'), ('nft', 'NFT')], default='cash', max_length=50, verbose_name='salary type')),
                ('salary', models.CharField(max_length=50, verbose_name='salary amount')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('location', models.ForeignKey(default='ww', on_delete=django.db.models.deletion.SET_DEFAULT, to='vacancies.location', verbose_name='location')),
            ],
            options={
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='VacancyPosition',
            fields=[
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'vacancy position',
                'verbose_name_plural': 'vacancy positions',
            },
        ),
        migrations.CreateModel(
            name='VacancyTag',
            fields=[
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'vacancy tag',
                'verbose_name_plural': 'vacancy tags',
            },
        ),
        migrations.CreateModel(
            name='VacancyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('cv', models.FileField(upload_to='vacancies/cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pdf', 'md'])], verbose_name='CV')),
                ('applicant', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
                ('vacancy', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='vacancies.vacancy', verbose_name='vacancy')),
            ],
            options={
                'verbose_name': 'vacancy request',
                'verbose_name_plural': 'vacancy requests',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancyposition', verbose_name='position'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='publicant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='publicant'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(to='vacancies.vacancytag', verbose_name='tags'),
        ),
    ]
