# Generated by Django 4.1.2 on 2022-10-21 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='communication',
            field=models.TextField(verbose_name='data for getting in touch with you *'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(max_length=50, verbose_name='company name *'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company_twitter',
            field=models.URLField(verbose_name='company twitter URL *'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company_website',
            field=models.URLField(verbose_name='company website URL *'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='description *'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='publicant'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=50, verbose_name='salary amount *'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='to_apply',
            field=models.URLField(verbose_name='where to apply (URL) *'),
        ),
    ]
